/* Generated by workflow/tool.py build from plan/objectives.md, plan/problems.md and plan/solutions.md.
   Do not edit: change the plan and rebuild. */
window.TRACE_CHAIN = {
  "O-001": {
    "type": "Objective",
    "name": "Manage all department projects in one place"
  },
  "O-002": {
    "type": "Objective",
    "name": "Present accurate project status to stakeholders"
  },
  "O-003": {
    "type": "Objective",
    "name": "Document everything about each project"
  },
  "O-004": {
    "type": "Objective",
    "name": "Protect the team from scope creep and project pressure"
  },
  "P-001": {
    "type": "Problem",
    "name": "No tool to create and manage projects",
    "home": "O-001",
    "also": []
  },
  "P-002": {
    "type": "Problem",
    "name": "No department-wide view of all projects",
    "home": "O-001",
    "also": []
  },
  "P-003": {
    "type": "Problem",
    "name": "Hard to see what each team member is working on",
    "home": "O-001",
    "also": [
      "O-004"
    ]
  },
  "P-004": {
    "type": "Problem",
    "name": "No single source of truth for project status",
    "home": "O-002",
    "also": [
      "O-001"
    ]
  },
  "P-005": {
    "type": "Problem",
    "name": "Stakeholders can't be shown only what concerns them",
    "home": "O-002",
    "also": []
  },
  "P-006": {
    "type": "Problem",
    "name": "Project files and context depend on each project manager",
    "home": "O-003",
    "also": []
  },
  "P-007": {
    "type": "Problem",
    "name": "No history log for projects",
    "home": "O-003",
    "also": [
      "O-004"
    ]
  },
  "P-008": {
    "type": "Problem",
    "name": "Requirements keep being added with no visible cost",
    "home": "O-004",
    "also": []
  },
  "P-009": {
    "type": "Problem",
    "name": "Stakeholders don't see the pile-up of concurrent projects",
    "home": "O-004",
    "also": [
      "O-002"
    ]
  },
  "P-010": {
    "type": "Problem",
    "name": "The cost of priority shifts is invisible",
    "home": "O-004",
    "also": []
  },
  "S-001": {
    "type": "Solution",
    "name": "Landing page",
    "home": "P-001",
    "also": []
  },
  "F-001": {
    "type": "Feature",
    "name": "Identify the visitor by role",
    "home": "S-001",
    "also": []
  },
  "F-002": {
    "type": "Feature",
    "name": "Route project manager to their dashboard",
    "home": "S-001",
    "also": [
      "S-003"
    ]
  },
  "F-003": {
    "type": "Feature",
    "name": "Placeholder for other roles",
    "home": "S-001",
    "also": []
  },
  "S-002": {
    "type": "Solution",
    "name": "Create and manage projects",
    "home": "P-001",
    "also": [
      "P-006"
    ]
  },
  "F-004": {
    "type": "Feature",
    "name": "Create a project — core details",
    "home": "S-002",
    "also": []
  },
  "F-005": {
    "type": "Feature",
    "name": "Definition tables: scope, problem statements, objectives",
    "home": "S-002",
    "also": []
  },
  "S-002.1": {
    "type": "Sub-solution",
    "name": "Project phases",
    "home": "S-002",
    "also": []
  },
  "F-006": {
    "type": "Feature",
    "name": "Timeline / phase builder",
    "home": "S-002.1",
    "also": []
  },
  "S-003": {
    "type": "Solution",
    "name": "Project manager home dashboard",
    "home": "P-001",
    "also": [
      "P-003"
    ]
  },
  "S-003.1": {
    "type": "Sub-solution",
    "name": "At-a-glance project status",
    "home": "S-003",
    "also": []
  }
};
