/* ===========================================================================
   Shared prototype logic: the localStorage-backed project store, working-day
   date math, derived project status, and small shared helpers.

   Traceability ("!" markers) now lives in prototype/trace/ (chain.js is
   generated by workflow/tool.py build; trace.js/trace.css are the marker
   component) - load those on every page instead of anything here.
   =========================================================================== */

/* ---------------------------------- STORE ---------------------------------- */

const STORE_KEY = "workflow_prototype_projects_v1";

const PHASES = [
  "Requirements gathering",
  "BA analysis document",
  "Development planning",
  "Development",
  "UAT",
  "Security testing",
  "Deployment",
  "Pilot on a small sample",
];

const HOLD_REASONS = [
  "Waiting for business approval",
  "Waiting for a requirement",
  "Resources pulled to another project",
];

const DEPARTMENTS_KEY = "workflow_prototype_departments_v1";

function loadProjects() {
  let list;
  try {
    list = JSON.parse(localStorage.getItem(STORE_KEY)) || [];
  } catch (e) {
    return [];
  }
  // Self-heal browsers that still have sample projects saved from an
  // earlier version of this prototype (sample seeding was removed).
  const cleaned = list.filter((p) => !p.sample);
  if (cleaned.length !== list.length) saveProjects(cleaned);
  return cleaned;
}
function saveProjects(list) {
  localStorage.setItem(STORE_KEY, JSON.stringify(list));
}
function addProject(project) {
  const list = loadProjects();
  list.push(project);
  saveProjects(list);
}
function updateProject(project) {
  const list = loadProjects();
  const i = list.findIndex((p) => p.id === project.id);
  if (i === -1) { addProject(project); return; }
  list[i] = project;
  saveProjects(list);
}
function getProject(id) {
  return loadProjects().find((p) => p.id === id) || null;
}
function loadDepartments() {
  try {
    return JSON.parse(localStorage.getItem(DEPARTMENTS_KEY)) || [];
  } catch (e) {
    return [];
  }
}
function addDepartment(name) {
  const list = loadDepartments();
  if (!list.includes(name)) {
    list.push(name);
    localStorage.setItem(DEPARTMENTS_KEY, JSON.stringify(list));
  }
}

const CUSTOM_HOLD_REASONS_KEY = "workflow_prototype_hold_reasons_v1";
function loadCustomHoldReasons() {
  try {
    return JSON.parse(localStorage.getItem(CUSTOM_HOLD_REASONS_KEY)) || [];
  } catch (e) {
    return [];
  }
}
function addCustomHoldReason(name) {
  const list = loadCustomHoldReasons();
  if (!list.includes(name)) {
    list.push(name);
    localStorage.setItem(CUSTOM_HOLD_REASONS_KEY, JSON.stringify(list));
  }
}

function uid() {
  return "p_" + Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
}

/* ------------------------------- DATE MATH ------------------------------- */
/* Simple working-day (Mon-Fri) math. No holiday calendar - good enough for
   a prototype, matches the unit phases already use ("planned work days"). */

function parseDate(s) {
  if (!s) return null;
  const [y, m, d] = s.split("-").map(Number);
  return new Date(y, m - 1, d);
}
function fmtDateISO(d) {
  return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0");
}
function todayISO() {
  return fmtDateISO(new Date());
}
/* Working days strictly between two ISO date strings (exclusive of start,
   inclusive of end); 0 or negative if end is not after start. */
function workingDaysBetween(startStr, endStr) {
  const start = parseDate(startStr), end = parseDate(endStr);
  if (!start || !end || end <= start) return 0;
  let n = 0;
  const d = new Date(start);
  d.setDate(d.getDate() + 1);
  while (d <= end) {
    const day = d.getDay();
    if (day !== 0 && day !== 6) n++;
    d.setDate(d.getDate() + 1);
  }
  return n;
}
/* ISO date `days` working days after startStr (day 0 = startStr itself). */
function addWorkingDays(startStr, days) {
  const start = parseDate(startStr);
  if (!start || !days) return startStr;
  const d = new Date(start);
  let added = 0;
  while (added < days) {
    d.setDate(d.getDate() + 1);
    const day = d.getDay();
    if (day !== 0 && day !== 6) added++;
  }
  return fmtDateISO(d);
}

/* ------------------------------- HOLD / STATUS ------------------------------- */
/* F-007: a hold's effective working-day count, for the end-date calculation
   (F-006 amendment) and for "how many days on hold" on the dashboard. */
function holdWorkingDays(hold) {
  if (!hold) return 0;
  if (hold.mode === "work-days") return hold.workDays || 0;
  if (hold.mode === "until-date" && hold.untilDate) return workingDaysBetween(hold.startedAt, hold.untilDate);
  if (hold.mode === "open-ended") return workingDaysBetween(hold.startedAt, todayISO());
  return 0;
}
function holdDurationNote(hold) {
  if (hold.mode === "until-date") return `until ${hold.untilDate || "?"}`;
  if (hold.mode === "work-days") return `for ${hold.workDays || 0} working day${hold.workDays === 1 ? "" : "s"}`;
  return "open-ended";
}

/* The project's status: launched and on-hold are manual (set by the project
   manager, per F-007/F-009); planned/active need no field of their own -
   they follow from the start date already on file. */
function projectStatus(project) {
  if (project.launched) return "launched";
  if (project.hold) return "hold";
  if (!project.startDate || project.startDate > todayISO()) return "planned";
  return "active";
}

/* F-006 amendment: start date + summed phase work-days + any hold duration. */
function calcEndDate(project) {
  if (!project.startDate) return null;
  const phaseDays = (project.phases || []).reduce((s, p) => s + (p.workDays || 0), 0);
  const holdDays = holdWorkingDays(project.hold);
  return addWorkingDays(project.startDate, phaseDays + holdDays);
}

/* Derive an "At-a-glance project status" (S-003.1) line for a project. */
function atAGlanceLine(project) {
  const status = projectStatus(project);
  if (status === "launched") {
    return { text: "Launched", tone: "active" };
  }
  if (status === "hold") {
    const days = holdWorkingDays(project.hold);
    return {
      text: `On hold ${days} working day${days === 1 ? "" : "s"} (${holdDurationNote(project.hold)}) — ${project.hold.reason}`,
      tone: "hold",
    };
  }
  if (status === "planned") {
    return { text: project.startDate ? `Planned — starts ${project.startDate}` : "Planned — no start date set", tone: "planned" };
  }
  // active: no phase-progress-reporting feature yet, so the only honest
  // signal is which phase comes first in the plan.
  if (project.phases && project.phases.length) {
    return { text: `Active — first phase: ${project.phases[0].name}`, tone: "active" };
  }
  return { text: "Active — no phases planned yet", tone: "active" };
}

function fmtDate(d) {
  if (!d) return "";
  return d;
}

/* Escape untrusted, user-typed text before it goes into innerHTML anywhere
   (project names, custom phase names, list entries, department names). */
function escHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
